--PERSON
INSERT INTO "PERSON" (ID,NAME) VALUES (1,'Jonas');
INSERT INTO "PERSON" (ID,NAME) VALUES (2,'Marina');
--TRANSACTION_TYPE
INSERT INTO "TRANSACTIONTYPE" (ID,POSITIVE,TEXT) VALUES (1,true,'Credit');
INSERT INTO "TRANSACTIONTYPE" (ID,POSITIVE,TEXT) VALUES (2,false,'Debit');
--CATEGORY
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (1,'Income',null);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (2,'Expense',null);
--Income
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (3,'Salário',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (4,'Adicional de Qualificação',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (5,'Anuênios / Triênios',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (6,'FCT',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (7,'Férias',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (8,'13º Salário',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (9,'Receita extra',1);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (10,'Outros',1);
--Expense
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (11,'Alimentação',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (12,'Mercado',11);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (13,'Ticket Alimentação',11);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (14,'Outros',11);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (15,'Habitação',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (16,'Prestação Caixa',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (17,'Prestação Pai',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (18,'Condomínio',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (19,'NET',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (20,'Energia elétrica',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (21,'Gás',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (77,'IPTU',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (22,'Celular',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (23,'Diarista',15);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (24,'Outros',15);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (25,'Saúde',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (26,'CASSI / SERPRO',25);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (27,'Sulamerica Seguros',25);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (28,'Plano Odontológico',25);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (29,'Academia',25);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (30,'Outros',25);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (31,'Transporte',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (32,'Público',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (33,'Combustível',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (34,'Seguro',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (35,'IPVA',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (36,'Manutenção',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (37,'Licenciamento',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (38,'Rav4 EUA',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (39,'Vale transporte',31);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (40,'Outros',31);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (41,'Pessoais',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (42,'Higiene Pessoal (cabelo, ...)',41);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (43,'Vestuário',41);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (44,'Presentes',41);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (45,'Doações',41);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (46,'Outros',41);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (47,'Lazer',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (48,'Cinema / Teatro / Shows',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (49,'Passagem aérea ',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (50,'Custos Extras de Viagem',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (51,'Hotel',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (52,'Aluguel de carro ',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (53,'Restaurantes / Festas',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (54,'Futebol',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (55,'Clube do Cocotá',47);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (56,'Outros',47);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (57,'Casamento',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (58,'Casa de festas',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (59,'Foto / Filmagem',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (60,'Vestido de Noiva',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (61,'Bem casado',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (62,'Buquê',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (63,'Hotel',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (64,'Padre',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (65,'Certidão de Habilitação',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (66,'Caio Lima',57);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (67,'Outros',57);
--
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (68,'Encargos Financeiros',2);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (69,'Previdência Social',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (70,'Previdência Privada',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (71,'Imposto de Renda',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (72,'Adiantamento a Pessoal',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (73,'Adiantamento do 13º',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (74,'Contribuição Sindical',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (75,'Transferências para EUA',68);
INSERT INTO "CATEGORY" (ID,TEXT,ID_PARENT) VALUES (76,'Tarifas Bancárias',68);
--

INSERT INTO "TRANSACTION" (ID,ID_TYPE,ID_CATEGORY,VALUE) VALUES (1,1,3,5934.59);














